### ISSUE TITLE
Adding more specific examples

### ISSUE THREAD

**Issue by ZASMan** [ice-cube-ruby/ice_cube#434]
I've found the documentation a little confusing. Can you add a line to the documentation or a link to an example where you can use icecube to send an email daily? I see how you set up ice cube in a model, but I don't see any examples where someone actually *does something* with it like send an email. Thanks!

**Comment by saiqulhaq** [comment]
you may check this out for more examples
[https://gist.github.com/nathancolgate/4998196](https://gist.github.com/nathancolgate/4998196)
