### ISSUE TITLE
Ruby 2.5 compatibility: Deserialized datetime value from YAML has no timezone

### ISSUE THREAD

**Issue by joealba** [ice-cube-ruby/ice_cube#435]
Beginning in Ruby 2.5 (https://github.com/ruby/psych/pull/316), Psych no longer deserializes a YAML datetime value into the local timezone.  The deserialized value respects the offset, but you wind up with a Time object with no timezone.  It's understandably less surprising behavior from Psych's point of view, but it means that DST calculations will be incorrect unless you apply a timezone to the deserialized value.

```
require "psych"
ENV["TZ"] = "EST"

time = Time.new(2018, 1, 25, 12, 0, 0, "+02:00")
yaml = Psych.dump(time)
restored = Psych::load yaml
puts restored.zone

## Ruby 2.4.3

yaml          # => "--- 2018-01-25 12:00:00.000000000 +02:00\n...\n"
time          # => 2018-01-25 12:00:00 +0200
restored      # => 2018-01-25 05:00:00 -0500
restored.zone # => "EST"


## Ruby 2.5.0

yaml          # => "--- 2018-01-25 12:00:00.000000000 +02:00\n...\n"
time          # => 2018-01-25 12:00:00 +0200
restored      # => 2018-01-25 12:00:00 +0200
restored.zone # => nil
```

Rather than submitting a PR with my own solution, I really wanted to open the issue and discuss your preferences.  

The gem could be configured to opt into the previous deserialization behavior -- or default to the previous behavior until a minor revision bump deprecates it.  It'd also be great to discuss your preferred way to transition ice_cube to the new ActiveSupport::TimeWithZone serialization format, which includes the timezone.

**Comment by joealba** [comment]
Also relevant: https://github.com/rails/rails/commit/e9bd957064a040fdd80e2b6d3fb0b793ccb9cce1

**Comment by CodingAnarchy** [comment]
This is a _major_ issue for me, as it is resulting in `next_occurrence(Date)` producing the same date as is fed into it in many cases, due to the loss of the time zone information. If someone has a solution, it needs to happen sooner rather than later.

**Comment by pacso** [comment]
Closing this as Ruby 2.5 is no longer supported
