### ISSUE TITLE
Ruby 2.5 compatibility: Argument error for finding occurrences with dates

### ISSUE THREAD

**Issue by CodingAnarchy** [ice-cube-ruby/ice_cube#436]
On current master with the following schedule:

#<IceCube::Schedule:0x00007fa19e9c03f0 @start_time=2018-02-19 00:00:00 -0500, @all_recurrence_rules=[#<IceCube::WeeklyRule:0x00007fa1a03e3cc8 @validations={:interval=>[#<IceCube::Validations::WeeklyInterval::Validation:0x00007fa1a03e3700 @interval=1, @week_start=:sunday>], :base_hour=>[#<IceCube::Validations::ScheduleLock::Validation:0x00007fa1a03e39d0 @type=:hour>], :base_min=>[#<IceCube::Validations::ScheduleLock::Validation:0x00007fa1a03e3930 @type=:min>], :base_sec=>[#<IceCube::Validations::ScheduleLock::Validation:0x00007fa1a03e3890 @type=:sec>], :day=>[#<IceCube::Validations::Day::Validation:0x00007fa1a03e2f58 @day=1>]}, @interval=1, @week_start=:sunday, @time=2018-02-27 00:00:00 -0500, @start_time=2018-02-19 00:00:00 -0500, @uses=2>], @all_exception_rules=[], @unit=:week>

I'm getting this error:

```
schedule.previous_occurrence(Date.current)
*** ArgumentError Exception: argument out of range
```

Casting the date with `to_time` works:

```
(byebug) schedule.previous_occurrence(Date.current.to_time)
2018-02-26 00:00:00 -0500
```

This was not a problem Ruby 2.4.1, but arose in the process of an upgrade to Ruby 2.5.

**Comment by CodingAnarchy** [comment]
Investigating leads me to believe this is related to issue #435 regarding `psych` returning times without zones in the YAML deserialization.

**Comment by CodingAnarchy** [comment]
Further investigation leads to the result that `build_in_zone` in TimeUtil assumes that if the reference does not have a time zone, all the arguments are there for building a time using `Time.new(*args << reference.utc_offset)`.  The date does not have the last three arguments (hours, minutes, and seconds) and so this building of the time fails.

I'm going to work on a PR to fix this problem with `build_in_zone`, at least.

**Comment by iarobinson** [comment]
When upgrading an older app from a previous version of Ruby to 2.5.1, our application was having an `out of range` error. This was solved by changing the following:

`(Time.now).to_date`

to

`(Time.now).to_time`

**Comment by pacso** [comment]
Closing this as Ruby 2.5 is no longer supported
