### ISSUE TITLE
hour_of_day not working properly with daily rule

### ISSUE THREAD

**Issue by rbarrera87** [ice-cube-ruby/ice_cube#440]
I found that when I create an schedule with `daily` and `hour_of_day` rules, `next_occurrence` is not using the `daily` rule, only `hour_of_day`. Take the following example: 

```ruby
current_time = Time.current
# => Mon, 02 Apr 2018 13:38:25 PDT -07:00
schedule = IceCube::Schedule.new(current_time)
rule = IceCube::Rule.daily(2).hour_of_day(17)
schedule.add_recurrence_rule(rule)
schedule.next_occurrence
# => Mon, 02 Apr 2018 17:39:40 PDT -07:00
# I think next_occurrence should be 2 days later ( Mon, 04 Apr 2018 17:39:40 PDT -07:00)
schedule.to_s
#=> "Every 2 days on the 17th hour of the day"
```
If I just add the daily rule it work as expected
```ruby
schedule = IceCube::Schedule.new(current_time)
rule = IceCube::Rule.daily(2)
schedule.add_recurrence_rule(rule)
schedule.next_occurrence
# => Wed, 04 Apr 2018 13:39:40 PDT -07:00
```
Or perhaps I am missing something 🤔 What I do want to have here is a schedule of `Every 2 days` meaning after 2 days `on the 17th hour of the day`.

Thank you!

**Comment by rbarrera87** [comment]
**Update:** I realized that is happening only when I have a **timezone** set to something different to `UTC`
```ruby
Time.zone
# => #<ActiveSupport::TimeZone:0x00000000073d5b10 @name="Pacific Time (US & Canada)", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: America/Los_Angeles>>
Time.zone = 'UTC'
# => "UTC"
Time.zone
# => #<ActiveSupport::TimeZone:0x000000000b11dce8 @name="UTC", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: Etc/UTC>>
t = Time.current
# => Mon, 02 Apr 2018 20:55:32 UTC +00:00
schedule = IceCube::Schedule.new(t)
rule = IceCube::Rule.daily(2).hour_of_day(17)
schedule.add_recurrence_rule(rule)
schedule.next_occurrence
# => Wed, 04 Apr 2018 17:55:32 UTC +00:00
```

**Comment by pacso** [comment]
In your first example, you created the schedule at 13:38, and asked for the `next_occurrence`. This was at 17:38 the same day. This is correct.

In your second example, you created the schedule at 20:55, and asked for the `next_occurrence`. Since you're already beyond the 17th hour, it correctly gave you the next one in 2 days time.

This seems to be working as designed?
