### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by bugdimes** [ice-cube-ruby/ice_cube#516]
homepage: https://seejohnrun.github.com/ice_cube 

and quick introduction: https://seejohnrun.github.com/ice_cube/static/ice_cube_ruby_nyc.pdf

**Comment by pacso** [comment]
Yep, it's a known issue. If you switch to `github.io` then they'll work.

> homepage: https://seejohnrun.github.io/ice_cube
> 
> and quick introduction: https://seejohnrun.github.io/ice_cube/static/ice_cube_ruby_nyc.pdf

This issue will be redundant shortly, as we're moving `ice_cube` to it's own organisation within GitHub. I'll leave this issue open for now, and we can close it once @seejohnrun has moved the repo.

**Comment by captproton** [comment]
Feb 22, 2022, links still need to be updated in the gemspec.

**Comment by webrails** [comment]
Github.io links in @pacso's response from 10 Dec 2021 don't work for me (404).

**Comment by pacso** [comment]
They'll be fixed in the next release.

**Comment by danielricecodes** [comment]
> Yep, it's a known issue. If you switch to `github.io` then they'll work.
> 
> > homepage: https://seejohnrun.github.io/ice_cube
> > and quick introduction: https://seejohnrun.github.io/ice_cube/static/ice_cube_ruby_nyc.pdf
> 
> This issue will be redundant shortly, as we're moving `ice_cube` to it's own organisation within GitHub. I'll leave this issue open for now, and we can close it once @seejohnrun has moved the repo.

Broken again as of May 16th, 2023 :-/

**Comment by pacso** [comment]
Was fixed in #553 and will be updated on RubyGems site once a new release is deployed
