### ISSUE TITLE
Psych::DisallowedClass: Tried to load unspecified class: Time with Psych v4

### ISSUE THREAD

**Issue by jeffblake** [ice-cube-ruby/ice_cube#520]
On `psych` 4.0, the following error is raised: 

`Psych::DisallowedClass: Tried to load unspecified class: Time`

After accessing a serialized schedule on an AR model, such as:

`serialize :schedule, IceCube::Schedule`

Works fine with Psych 3.3.2

**Comment by pacso** [comment]
Hey @jeffblake, this sounds very much like an issue with Psych 4.0 rather than IceCube. 

I'm not sure what you're expecting us to do with this? If you have a failing test for this gem, or a change you want to suggest, then please submit a PR.

**Comment by jeffblake** [comment]
Hi @pacso Here's an example fix: https://github.com/sparklemotion/mechanize/pull/589/files

https://github.com/ruby/psych/issues/503

**Comment by pacso** [comment]
Hi again @jeffblake 

I've created [a new PR](https://github.com/ice-cube-ruby/ice_cube/pull/521) for the latest Ruby, and have replicated the issue you've mentioned. Thanks for pointing it out ... will get a fix sorted before the next release.

**Comment by pacso** [comment]
@jeffblake - could you possibly test with the branch from PR #521 please?

**Comment by jeffblake** [comment]
@pacso My tests pass! Thanks.

**Comment by pacso** [comment]
Great, thanks for checking! I'll merge it now :)

**Comment by Aesthetikx** [comment]
Can we get a rubygems release for this? ❤️

**Comment by gustavompo** [comment]
+1 for a release

**Comment by jeffblake** [comment]
Bump for release please.

**Comment by pacso** [comment]
Hey everyone. 

We have a problem in terms of cutting a release at the moment. One of the previous commits fixed a bug, but introduced another. By rolling it back we remove the new bug, but reintroduce the old one. Neither is a viable option really.

I've been struggling for time recently, but should be able to dedicate myself to fixing this soon. Once done we'll cut a new release and get both bugs sorted properly.

Sorry for the delay!

**Comment by adfoster-r7** [comment]
It would be great if there was a release available for this; is there anything I can do to help? 🤞
