### ISSUE TITLE
Minutely recurrence windows by day of week?

### ISSUE THREAD

**Issue by sethaddison** [ice-cube-ruby/ice_cube#529]
I am using IceCube to create calendar appointment windows per day of week (following the Calendly model). User can specify specify which days they take appointments, appointment duration, and then a start time and end time for that particular day. 
**Example:**
Appointment duration: 15 Minutes
Sunday: 9:15am - 5:30pm
Monday: 10am - 1pm

I'm thinking I should create separate recurrence rules for each day of week.  Where I'm getting stuck is on the start and end time of the daily window (down to the correct minute). 

For Sunday, I know I can do `schedule.rrule IceCube::Rule.minutely(15).day(:sunday).hour_of_day((9..17).to_a)` to get 9 to 5, but do I get 9:15 to 5:30?

**Comment by sethaddison** [comment]
Any chance I could get a quick reply on this? cc @seejohnrun @avit @pacso

**Comment by buxbunny110** [comment]
Hello, the way how I did this is to incorporate plain rails Time.between? method with weekday recurrence conjunction, because I had similar issue and I could not find the way to chain them together.

**Comment by pacso** [comment]
Depending on what you're trying to achieve, you don't need to restrict the rule to the day and hours. You can just use something like this:

```ruby
> s = IceCube::Schedule.new
> s.start_time = Time.new(2024, 07, 21, 9, 15)
> s.add_recurrence_rule IceCube::Rule.minutely(15)
> s.end_time = Time.new(2024, 7, 21, 17, 30)
```
