### ISSUE TITLE
Possible to release the unreleased changes?

### ISSUE THREAD

**Issue by anjiemerchant** [ice-cube-ruby/ice_cube#541]
hi there,

wondering if it's possible to make a release at some point? we'd love to take advantage of the fix that:
- Includes exrules when exporting a schedule to YAML, JSON or a Hash. (https://github.com/ice-cube-ruby/ice_cube/pull/519) by [@pacso](https://github.com/pacso)

thanks!

**Comment by northeastprince** [comment]
@seejohnrun @pacso is this gem still being maintained?

**Comment by pacso** [comment]
Hi @northeastprince,

Yes - this is still being maintained. However, we can use all the help we can get. If you're able to review PRs, issues, and submit fixes, I'm more than happy to get things merged in and get a release out. I've just been extremely tight for time over the last few months.

I will be dedicating more time to this in 2024, so a new release will be coming one way or another.

**Comment by pacso** [comment]
@seejohnrun is giving me permission to release builds via RubyGems, so I expect to make a new release this month. I'll close this issue for now.
